In [1]:
from keras.models import load_model

model = load_model('second_model.h5')

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.


## Predicting

In [4]:
from keras.preprocessing.image import ImageDataGenerator

test_gen = ImageDataGenerator(rescale= 1./255)

test_data = test_gen.flow_from_directory('dataset/test_set', target_size=(64,64), batch_size=64, class_mode='binary')

Found 2000 images belonging to 2 classes.


In [8]:
model.evaluate_generator(generator=test_data, steps=64)

[0.33235684084892275, 0.8965]

In [10]:
test_data.class_indices

{'cats': 0, 'dogs': 1}

In [34]:
predict_data = ImageDataGenerator(rescale=1./255).flow_from_directory('dataset/single_prediction', target_size=(64,64), batch_size=1, shuffle=False)

Found 4 images belonging to 1 classes.


In [35]:
model.predict_generator(predict_data, steps=1, verbose=1)

1/1 [==============================] - 0s 42ms/step


array([[4.3597106e-06]], dtype=float32)

In [36]:
model.predict_generator(predict_data, steps=1, verbose=1)

1/1 [==============================] - 0s 135ms/step


array([[0.7436045]], dtype=float32)

In [37]:
model.predict_generator(predict_data, steps=1, verbose=1)

1/1 [==============================] - 0s 43ms/step


array([[4.3597106e-06]], dtype=float32)

In [38]:
model.predict_generator(predict_data, steps=1, verbose=1)

1/1 [==============================] - 0s 144ms/step


array([[0.7436045]], dtype=float32)